pull_request_rules:
  - name: Automatic merge
    description: Merge when PR passes all branch protection and has label automerge
    conditions:
      - label = automated
      - author = twoneis
      - check-success = check-flake
    actions:
      merge: 
