name: CI

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '5 0 * * 6' # runs weekly on Saturday at 00:05 (give time for flake lock update)

env: 
  TARGET_FLAKE: github:${{ github.repository }}/${{ inputs.sha || github.sha }}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: Run `nix build`
        run: GC_DONT_GC=1 nix build --accept-flake-config --show-trace --log-lines
          10000 --fallback "$TARGET_FLAKE#"'nixosConfigurations.surface.config.boot.kernelPackages.kernel'
