name: check-flake

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Check nix flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4 
